#!/usr/bin/env python3
"""Writes the December 26 to January 31 connected-quiz drafts.

Scratch editorial tooling, not used by the runtime or importers. Run from the
repository root after editorial/tools/runway/b1226.py:

    python3 editorial/tools/connected-quiz/build_dec_jan_cycle.py

It (re)writes editorial/batches/2026-12-26-01-31-connected-quiz/ from the
records below: new draft questions (proposed pack
170-connected-december-26-january-31.json) and relation proposals that link
unchanged published questions to the new draft events.

Every ledger entry is source_verified, never approved. Link proposals record a
snapshot hash of the canonical question as inspected
(json.dumps(question, separators=(",", ":")) in file key order, the same scheme
as the October cycles), so a later change to that question is detectable.
"""
import collections
import glob
import hashlib
import json
import os

CHECKED = "2026-10-01"
BATCH_ID = "2026-12-26-01-31-connected-quiz"
PACK = "170-connected-december-26-january-31.json"
EVENT_BATCHES = [
    "2026-12-26-01-01-historical-events",
    "2027-01-02-08-historical-events",
    "2027-01-09-15-historical-events",
    "2027-01-16-22-historical-events",
    "2027-01-23-31-historical-events",
]
BR = "Encyclopaedia Britannica - "
NOTE_NEW = ("Draft researched and source-checked by Claude; awaiting owner content review. "
            "Relation: {rel} Distractors checked for exclusivity under the question's wording; "
            "difficulty is an editorial estimate, not user-tested.")
NOTE_LINK = ("Relationship review only; original question and answer are unchanged and remain "
             "published. New relation is unapproved. {extra}")


def otd(month, day, note):
    return (f"https://www.britannica.com/on-this-day/{month}-{day}",
            (f"{BR}On This Day: {month} {day}", f"Britannica On This Day ({month[:3]} {day}): {note}"))


SRC = dict([
    otd("December", 26, "1967: Wham-O issued a U.S. patent for 'a saucer-shaped throwing implement'."),
    otd("December", 27, "1949: 'The Dutch formally relinquished control over Indonesia' after its declaration of independence."),
    otd("December", 28, "1895: first public demonstration of the Cinematographe at the Grand Cafe in Paris; 1065: Westminster Abbey consecrated."),
    otd("December", 29, "1845: Congress approved the annexation of 'the independent Republic of Texas'; 1809: Gladstone, prime minister four times (1868-74, 1880-85, 1886, 1892-94), born in Liverpool."),
    otd("December", 30, "1922: USSR established 'with its capital in Moscow'; 1853: the US acquired nearly 30,000 square miles of northern Mexican territory with the Gadsden Purchase; 1902: Robert Falcon Scott set a new record for reaching the farthest point south."),
    otd("December", 31, "2004: 'Taipei 101 opened in Taipei, Taiwan. At 1,667 feet (508 metres), it was the tallest building in the world'; 1857: Queen Victoria named Ottawa the national capital of Canada; 1999: the United States officially handed over control of the Panama Canal to Panama."),
    otd("January", 1, "1999: eleven EU countries changed to the euro; 2026: Bulgaria adopted the euro; 1804: Haiti declared independence from France; 1863: Emancipation Proclamation, freeing enslaved people in the Confederacy; 1959: Batista fled Cuba, toppled by rebel forces led by Fidel Castro."),
    otd("January", 2, "1492: Ferdinand II and Isabella I captured Granada; 1905: Russian forces surrendered Port Arthur to the Japanese; 2004: NASA's Stardust collected dust grains from comet Wild 2."),
    otd("January", 3, "1892: J.R.R. Tolkien born; 2019: 'Chang'e 4, carrying the Yutu-2 rover, landed on the Moon's far side.'"),
    otd("January", 4, "2010: 'Burj Khalifa, the world's tallest building, officially opened in Dubai'; 1948: Burma, 'today called Myanmar', gained independence from Great Britain."),
    otd("January", 5, "1933: construction began on the Golden Gate Bridge, 'which connects San Francisco with Marin county'; 1914: Henry Ford raised his workers' pay from $2.40 to $5.00 a day."),
    otd("January", 6, "1540: 'Henry VIII of England married Anne of Cleves, the fourth of his six wives.'"),
    otd("January", 7, "1968: Surveyor 7 launched; it soft-landed on the Moon; 1979: Vietnamese forces took Phnom Penh, Cambodia, removing the Khmer Rouge."),
    otd("January", 10, "1776: Thomas Paine published Common Sense; 1920: 'The League of Nations was established in Geneva'; 1946: 'The first United Nations General Assembly met in London.'"),
    otd("January", 12, "1959: 'Berry Gordy took a major step toward transforming American music on this day in 1959, when he launched Tamla Records.'"),
    otd("January", 13, "1898: Zola's open letter 'J'accuse' denounced the general staff over the 1894 treason court-martial of Alfred Dreyfus."),
    otd("January", 14, "2005: the Huygens probe landed on Saturn's largest moon, Titan; 1900: Tosca premiered in Rome's Costanzi Theatre."),
    otd("January", 17, "1929: 'Popeye, a sailor known for his love of spinach, made his debut' in Thimble Theatre."),
    otd("January", 19, "1809: Edgar Allan Poe born in Boston; 1853: Verdi's Il trovatore premiered in Rome."),
    otd("January", 21, "1976: Concorde, 'built with funding from the British and French governments, began regular service'; 1793: Louis XVI executed by guillotine in Paris."),
    otd("January", 8, "1912: 'The African National Congress was founded.'"),
    otd("January", 17, "1893: Queen Liliuokalani deposed by a provisional government led by Sanford Ballard Dole."),
    otd("January", 26, "1905: world's largest diamond, over a pound, found at the Premier Mine in South Africa; 1950: 'India became a republic, achieving full independence from Great Britain.'"),
    otd("January", 30, "1969: the Beatles performed together for the last time; 1948: Gandhi assassinated."),
    otd("December", 5, "Existing source of mozart-death-age: Mozart died in Vienna on December 5, 1791. Not re-fetched; inherited."),
    otd("January", 22, "1984: Apple aired a commercial during Super Bowl XVIII directed by Ridley Scott and inspired by Orwell's Nineteen Eighty-four; 1788: Lord Byron born."),
    otd("January", 24, "1984: 'Steve Jobs introduced Apple's revolutionary computer Macintosh.'"),
    otd("January", 28, "1986: Challenger exploded 73 seconds after liftoff from Florida, killing all seven aboard."),
    otd("January", 29, "1860: Anton Chekhov born; 1845: 'The Raven' first published; 1886: Karl Benz patented the first practical automobile powered by an internal-combustion engine."),
])
SRC.update({
    "https://www.westminster-abbey.org/abbey-commemorations/royals/edward-the-confessor-and-edith": ("Westminster Abbey - Edward the Confessor and Edith",
        "Westminster Abbey: Edward built a new Norman-style church to replace the Saxon church; consecrated on 28 December 1065, but the king was ill and unable to attend; he died on the night of 4-5 January 1066."),
    "https://www.tshaonline.org/handbook/entries/annexation": ("Texas State Historical Association - Handbook of Texas: Annexation",
        "TSHA: Congress passed the annexation resolution on February 28, 1845; Texas legally entered the Union on December 29, 1845; authority transferred from the republic to the state on February 19, 1846."),
    "https://www.britannica.com/biography/Charles-Babbage": (BR + "Charles Babbage",
        "Britannica: born December 26, 1791, London; designed the Difference Engine (from 1823) and, in the mid-1830s, the Analytical Engine, 'the forerunner of the modern digital computer'; Ada Lovelace's 1843 notes on it."),
    "https://www.britannica.com/topic/Hagia-Sophia": (BR + "Hagia Sophia",
        "Britannica: in 'Constantinople (now Istanbul)'; built under Justinian I, completed in 537; a mosque after 1453, a museum from 1935, a mosque again from 2020."),
    "https://www.britannica.com/biography/Charles-Darwin": (BR + "Charles Darwin",
        "Britannica: 'The Beagle sailed from England on December 27, 1831'; map caption covers the voyage of 1831-36."),
    "https://www.britannica.com/biography/Johannes-Kepler": (BR + "Johannes Kepler",
        "Britannica: born December 27, 1571, Weil der Stadt; first law: 'the planets move in elliptical orbits with the Sun at one focus'."),
    "https://www.britannica.com/biography/Constance-Markievicz": (BR + "Constance Markievicz",
        "Britannica: elected to the House of Commons in December 1918; with the other Sinn Fein members she refused the oath of allegiance 'and, thus, did not take her seat'; minister of labour in the first Dail (1919-22)."),
    "https://www.britannica.com/place/Ireland": (BR + "Ireland",
        "Britannica Quick Facts: 'Official Name: Eire (Irish); Ireland (English)'; new constitution in 1937; left the Commonwealth as the Republic of Ireland in 1949."),
    "https://www.britannica.com/biography/Jose-Rizal": (BR + "Jose Rizal",
        "Britannica: executed by firing squad in Manila on December 30, 1896; Noli Me Tangere 'a passionate exposure of the evils of Spanish rule in the Philippines'."),
    "https://www.britannica.com/place/Times-Square": (BR + "Times Square",
        "Britannica: formerly Long Acre (Longacre) Square; 'renamed in 1904 for The New York Times, which opened its new offices in the Times Tower'; the Times began lowering a ball at midnight on New Year's Eve in 1907."),
    "https://www.britannica.com/topic/World-Trade-Organization": (BR + "World Trade Organization",
        "Britannica: 'The WTO began operations on January 1, 1995'; 'successor to the General Agreement on Tariffs and Trade (GATT), which was created in 1947'; headquartered in Geneva."),
    "https://www.britannica.com/biography/J-R-R-Tolkien": (BR + "J.R.R. Tolkien",
        "Britannica: 'born January 3, 1892, Bloemfontein, South Africa'."),
    "https://www.britannica.com/place/Hawaii-state": (BR + "Hawaii",
        "Britannica: 'Hawaii became the 50th U.S. state on August 21, 1959.'"),
    "https://www.britannica.com/topic/braille-writing-system": (BR + "Braille",
        "Britannica: characters 'made up of one to six raised dots arranged in a six-position matrix or cell'; invented by Louis Braille in 1824."),
    "https://www.britannica.com/topic/Waiting-for-Godot": (BR + "Waiting for Godot",
        "Britannica: by the Irish writer Samuel Beckett; published in French in 1952 as En attendant Godot; first produced in 1953; Vladimir and Estragon wait for Godot."),
    "https://science.nasa.gov/dwarf-planets/eris/": ("NASA Science - Eris",
        "NASA: Eris discovered Jan. 5, 2005, from 2003 Palomar data; its discovery helped trigger the debate leading to the IAU's 2006 definition of a planet, which reclassified Pluto as a dwarf planet."),
    "https://www.britannica.com/topic/Four-Freedoms": (BR + "Four Freedoms",
        "Britannica: January 6, 1941; 'the freedom of speech and expression, the freedom of worship, the freedom from want, and the freedom from fear.'"),
    "https://www.britannica.com/biography/Marian-Anderson": (BR + "Marian Anderson",
        "Britannica: barred from Constitution Hall by the DAR, she sang at the Lincoln Memorial on April 9, 1939, to 75,000 people; on January 7, 1955, first Black singer to perform as a member of the Metropolitan Opera."),
    "https://www.britannica.com/event/Fourteen-Points": (BR + "Fourteen Points",
        "Britannica: January 8, 1918; point 14: 'A general association of nations must be formed', the basis of the League of Nations."),
    "https://www.britannica.com/biography/Stephen-Hawking": (BR + "Stephen Hawking",
        "Britannica: born January 8, 1942, Oxford; A Brief History of Time: From the Big Bang to Black Holes (1988)."),
    "https://www.britannica.com/biography/Elvis-Presley": (BR + "Elvis Presley",
        "Britannica: born January 8, 1935, Tupelo, Mississippi; his Memphis estate Graceland remains one of the country's top tourist attractions."),
    "https://www.britannica.com/biography/Saint-Joan-of-Arc": (BR + "Saint Joan of Arc",
        "Britannica: byname the Maid of Orleans, from the 1429 victory at Orleans; trial began January 9, 1431, in Rouen."),
    "https://www.britannica.com/place/Rubicon": (BR + "Rubicon",
        "Britannica: a 'small stream that separated Cisalpine Gaul from Italy in the era of the Roman Republic'; Caesar crossed it in 49 BCE."),
    "https://www.britannica.com/biography/Edmund-Hillary": (BR + "Edmund Hillary",
        "Britannica: New Zealand mountain climber; reached Everest's summit May 29, 1953; died January 11, 2008, Auckland."),
    "https://www.britannica.com/biography/Amelia-Earhart": (BR + "Amelia Earhart",
        "Britannica: crossed the Atlantic alone May 20-21, 1932; left Honolulu January 11, 1935, landing in Oakland the next day."),
    "https://www.britannica.com/topic/Motown": (BR + "Motown",
        "Britannica: 'founded by Berry Gordy, Jr., in Detroit in January 1959'."),
    "https://www.britannica.com/event/Jasmine-Revolution": (BR + "Jasmine Revolution",
        "Britannica: Ben Ali stepped down and left the country on January 14, 2011; the uprising 'inspired a wave of similar protests throughout the Middle East and North Africa known as the Arab Spring.'"),
    "https://www.britannica.com/topic/British-Museum": (BR + "British Museum",
        "Britannica: established by act of Parliament in 1753 from the Sloane, Harley and Cotton collections; opened in 1759; collections housed in Montagu House, Great Russell Street."),
    "https://www.britannica.com/biography/Sally-Ride": (BR + "Sally Ride",
        "Britannica: one of six women in the 1978 astronaut group; first American woman in space on June 18, 1983, aboard Challenger (STS-7)."),
    "https://www.britannica.com/biography/Benjamin-Franklin": (BR + "Benjamin Franklin",
        "Britannica: 'born January 17 [January 6, Old Style], 1706, Boston, Massachusetts'."),
    "https://www.britannica.com/biography/William-I-emperor-of-Germany": (BR + "William I (emperor of Germany)",
        "Britannica: 'William was acclaimed German emperor ... at Versailles, in conquered France, on Jan. 18, 1871.'"),
    "https://www.britannica.com/biography/Edgar-Allan-Poe": (BR + "Edgar Allan Poe",
        "Britannica: born January 19, 1809, Boston; pioneered the modern detective story with 'The Murders in the Rue Morgue' (1841); 'The Raven' in the New York Mirror of January 29, 1845."),
    "https://www.britannica.com/biography/Barack-Obama": (BR + "Barack Obama",
        "Britannica: inaugurated January 20, 2009; U.S. senator from Illinois (2005-08); born in Honolulu."),
    "https://www.britannica.com/biography/Marie-Antoinette-queen-of-France": (BR + "Marie-Antoinette",
        "Britannica: queen consort of Louis XVI (1774-93); guillotined in Paris on October 16, 1793."),
    "https://www.britannica.com/place/Saint-Petersburg-Russia": (BR + "Saint Petersburg",
        "Britannica: 'Formerly (1914-24): Petrograd and (1924-91): Leningrad'."),
    "https://www.britannica.com/biography/Victoria-queen-of-United-Kingdom": (BR + "Victoria",
        "Britannica: died January 22, 1901, at Osborne, Isle of Wight; queen 1837-1901; succeeded by her son Edward VII."),
    "https://www.britannica.com/biography/Elizabeth-Blackwell": (BR + "Elizabeth Blackwell",
        "Britannica: born February 3, 1821, Counterslip, Bristol, England; graduated from Geneva Medical College, New York, in January 1849."),
    "https://www.britannica.com/topic/California-Gold-Rush": (BR + "California Gold Rush",
        "Britannica: gold found January 24, 1848, by James W. Marshall at John Sutter's mill on the American River, Coloma; 1849 arrivals called forty-niners."),
    "https://www.britannica.com/event/Chamonix-1924-Olympic-Winter-Games": (BR + "Chamonix 1924 Olympic Winter Games",
        "Britannica: January 25-February 5, 1924, the first Winter Olympics; 11-year-old Sonja Henie made her Olympic debut and 'finished last in the standings'."),
    "https://www.britannica.com/biography/Robert-Burns": (BR + "Robert Burns",
        "Britannica: born January 25, 1759, Alloway, Ayrshire; known for songs 'such as \"Auld Lang Syne.\"'"),
    "https://www.britannica.com/biography/Virginia-Woolf": (BR + "Virginia Woolf",
        "Britannica: born January 25, 1882, London; weekly gatherings in Bloomsbury with Clive Bell, Lytton Strachey and John Maynard Keynes became 'what came to be known as the Bloomsbury group'."),
    "https://www.britannica.com/topic/Cullinan-diamond": (BR + "Cullinan diamond",
        "Britannica: found 1905 at the Premier mine, Transvaal; about 3,106 carats rough; presented (1907) to King Edward VII; Cullinan I set in the Sovereign's Sceptre with Cross, Cullinan II in the Imperial Crown."),
    "https://www.britannica.com/place/Auschwitz": (BR + "Auschwitz",
        "Britannica: near the town of Oswiecim in southern Poland, in territory annexed by Germany; Soviet troops arrived January 27, 1945, finding 7,650 prisoners; 1.1 to 1.5 million people died there."),
    "https://www.britannica.com/biography/Wolfgang-Amadeus-Mozart": (BR + "Wolfgang Amadeus Mozart",
        "Britannica: born January 27, 1756, Salzburg; operas include The Marriage of Figaro (1786), Don Giovanni (1787) and The Magic Flute (1791)."),
    "https://www.britannica.com/topic/LEGO": (BR + "LEGO",
        "Britannica: based in Billund, Denmark; founded by Ole Kirk Christiansen in 1932; name from Danish leg godt, 'play well'; interlocking brick patented January 1958."),
    "https://www.britannica.com/event/Challenger-disaster": (BR + "Challenger disaster",
        "Britannica: January 28, 1986, 73 seconds after liftoff; seven astronauts died, including the teacher Christa McAuliffe; failed O-rings in the right solid rocket booster."),
    "https://www.britannica.com/topic/Pride-and-Prejudice": (BR + "Pride and Prejudice",
        "Britannica: published anonymously in 1813 by Jane Austen; heroine Elizabeth Bennet, hero Fitzwilliam Darcy."),
    "https://www.britannica.com/biography/Karl-Benz": (BR + "Karl Benz",
        "Britannica: 'a three-wheeled vehicle, the Motorwagen', internal-combustion powered, first ran in 1885, patented January 29, 1886."),
    "https://www.britannica.com/biography/Anton-Chekhov": (BR + "Anton Chekhov",
        "Britannica: born January 29 [January 17, Old Style], 1860, Taganrog; plays The Seagull, Uncle Vanya, Three Sisters, The Cherry Orchard."),
    "https://www.britannica.com/event/Salt-March": (BR + "Salt March",
        "Britannica: March-April 1930, Sabarmati Ashram to Dandi on the Arabian Sea, against the British salt tax."),
    "https://www.britannica.com/topic/Brexit": (BR + "Brexit",
        "Britannica: referendum June 23, 2016, some 52 percent voted to leave; the UK formally withdrew at 11:00 pm London time on January 31, 2020."),
    "https://www.britannica.com/biography/Franz-Schubert": (BR + "Franz Schubert",
        "Britannica: born January 31, 1797, near Vienna; Symphony in B Minor (Unfinished; 1822)."),
    "https://www.britannica.com/biography/Jackie-Robinson": (BR + "Jackie Robinson",
        "Britannica: born January 31, 1919, Cairo, Georgia; debuted with the Brooklyn Dodgers on April 15, 1947, breaking the color line."),
    "https://www.britannica.com/event/Battle-of-Stalingrad": (BR + "Battle of Stalingrad",
        "Britannica: 'Stalingrad (now Volgograd, Russia)', on the Volga; Paulus agreed to give himself up on January 31, 1943."),
    "https://science.nasa.gov/mission/cassini/spacecraft/huygens-probe/": ("NASA Science - Huygens probe",
        "NASA: the European Space Agency's Huygens probe landed on Titan on January 14, 2005, the first landing in the outer solar system."),
    # Sources of reused published questions, as cited in their canonical packs.
    "https://www.britannica.com/on-this-day/December-14": (BR + "On This Day: December 14",
        "Existing source of amundsen-first-south-pole; Amundsen reached the South Pole on December 14, 1911. Not re-fetched; inherited."),
    "https://pancanal.com/en/history-of-the-panama-canal/": ("Panama Canal Authority - History",
        "Existing source of panama-canal-transfer-year: transfer completed at noon on 31 December 1999. Not re-fetched; inherited."),
    "https://www.britannica.com/topic/Haitian-Revolution": (BR + "Haitian Revolution",
        "Existing source of haitian-revolution-outcome: Haiti declared independence in 1804. Not re-fetched; inherited."),
    "https://whc.unesco.org/en/list/314": ("UNESCO - Alhambra, Generalife and Albayzin, Granada",
        "Existing source of alhambra-nasrid-palace (Nasrid palaces in Granada). Not re-fetched; inherited."),
    "https://nhcp.gov.ph/jose-rizal/": ("National Historical Commission of the Philippines - Jose Rizal",
        "Existing source of identify-jose-rizal. Not re-fetched; inherited."),
    "https://www.loc.gov/pictures/item/2016651074/": ("Library of Congress - Liliuokalani portrait",
        "Existing source of identify-queen-liliuokalani: last reigning monarch of the Hawaiian Kingdom. Not re-fetched; inherited."),
    "https://www.britannica.com/biography/Winston-Churchill": (BR + "Winston Churchill",
        "Britannica: died January 24, 1965, London (aged 90); British prime minister for most of World War II."),
    "https://www.britannica.com/biography/Mahatma-Gandhi": (BR + "Mahatma Gandhi",
        "Existing source of identify-mahatma-gandhi. Not re-fetched; inherited."),
    "https://www.britannica.com/biography/Ada-Lovelace": (BR + "Ada Lovelace",
        "Existing source of identify-ada-lovelace: notes on Babbage's Analytical Engine. Not re-fetched; inherited."),
    "https://www.britannica.com/topic/Indian-Independence-Act-1947": (BR + "Indian Independence Act",
        "Existing source of india-independence-1947. Not re-fetched; inherited."),
    "https://www.nasa.gov/history/SP-4219/Chapter15.html": ("NASA History - SP-4219 Chapter 15",
        "Existing source of discovery-sts26-return-to-flight. Not re-fetched; inherited."),
    "https://www.nelsonmandela.org/biography": ("Nelson Mandela Foundation - Biography",
        "Existing source of south-africa-1994-president: the ANC won the April 1994 election. Not re-fetched; inherited."),
    "https://history.state.gov/milestones/1914-1920/paris-peace": ("Office of the Historian - Paris Peace Conference",
        "Existing source of versailles-league-created. Not re-fetched; inherited."),
    "https://history.state.gov/milestones/1914-1920/league": ("Office of the Historian - League of Nations",
        "Existing source of united-states-league-member. Not re-fetched; inherited."),
    "https://www.thebeatles.com/please-please-me": ("The Beatles - Please Please Me",
        "Existing source of beatles-home-city. Not re-fetched; inherited."),
})


def U(month, day):
    return f"https://www.britannica.com/on-this-day/{month}-{day}"


def mc(qid, difficulty, prompt, options, correct, explanation, sources, collections_, related):
    return {"id": qid, "type": "multiple_choice", "difficulty": difficulty, "publicationState": "draft",
            "prompt": prompt, "options": [{"id": i, "text": t} for i, t in options],
            "correctOptionId": correct, "explanation": explanation,
            "sources": [{"displayName": SRC[u][0], "url": u} for u in sources],
            "collectionIds": collections_, "relatedEventIds": related}


def tf(qid, difficulty, prompt, answer, explanation, sources, collections_, related):
    q = mc(qid, difficulty, prompt, [("true", "True"), ("false", "False")], "true" if answer else "false",
           explanation, sources, collections_, related)
    q["type"] = "true_false"
    return q


def order(qid, difficulty, prompt, items, correct, explanation, sources, collections_, related):
    return {"id": qid, "type": "chronological_ordering", "difficulty": difficulty, "publicationState": "draft",
            "prompt": prompt, "items": [{"id": i, "text": t} for i, t in items],
            "correctOrderItemIds": correct, "explanation": explanation,
            "sources": [{"displayName": SRC[u][0], "url": u} for u in sources],
            "collectionIds": collections_, "relatedEventIds": related}


S = "society-culture-and-ideas"
SCI = "science-and-innovation"
EX = "exploration-and-exchange"
LP = "leaders-and-power"
WC = "wars-and-conflicts"
REV = "revolutions"
WW = "world-wars"
AH = "ancient-history"
AR = "ancient-rome"

# (question, calendarDay, role, regions, eras, relation rationale)
NEW = [
    # Dec 26
    (mc("frisbee-patent-company", "easy",
        "Which toy company was granted a 1967 US patent for the flying disc best known as the Frisbee?",
        [("wham-o", "Wham-O"), ("mattel", "Mattel"), ("hasbro", "Hasbro"), ("parker-brothers", "Parker Brothers")], "wham-o",
        "Wham-O received the patent on December 26, 1967, for what it described as a saucer-shaped throwing implement.",
        [U("December", 26)], [SCI], ["frisbee-patent-issued-1967"]),
     "12-26", "featured", ["americas"], ["cold-war"],
     "Exact match on the featured patent; the distractors are other large US toy makers."),
    (mc("babbage-analytical-engine", "medium",
        "Charles Babbage's Analytical Engine, designed in the 1830s, is seen as the forerunner of what?",
        [("steam-locomotive", "The steam locomotive"), ("telegraph", "The electric telegraph"),
         ("digital-computer", "The modern digital computer"), ("typewriter", "The typewriter")], "digital-computer",
        "Babbage, born December 26, 1791, designed the Difference Engine and then the Analytical Engine, which Britannica calls the forerunner of the modern digital computer.",
        ["https://www.britannica.com/biography/Charles-Babbage"], [SCI], ["charles-babbage-born-1791"]),
     "12-26", "additional", ["europe"], ["early-modern", "1800-1945"],
     "Explains why Babbage's birth is worth marking; all distractors are 19th-century inventions."),
    # Dec 27
    (mc("hagia-sophia-modern-city", "easy",
        "Hagia Sophia was built in Constantinople. What is that city called today?",
        [("ankara", "Ankara"), ("istanbul", "Istanbul"), ("athens", "Athens"), ("izmir", "Izmir")], "istanbul",
        "Hagia Sophia, completed in 537 under Justinian I, stands in Istanbul. It became a mosque after 1453, a museum in 1935 and a mosque again in 2020.",
        ["https://www.britannica.com/topic/Hagia-Sophia"], [S], ["hagia-sophia-consecrated-537"]),
     "12-27", "featured", ["europe", "middle-east"], ["medieval"],
     "Locates the featured monument; Ankara is the tempting capital-city distractor."),
    (mc("beagle-voyage-length", "medium",
        "Roughly how long did Charles Darwin's voyage on HMS Beagle last?",
        [("one-year", "About one year"), ("two-years", "About two years"), ("five-years", "About five years"),
         ("ten-years", "About ten years")], "five-years",
        "The Beagle sailed from England on December 27, 1831, and the voyage lasted until 1836.",
        ["https://www.britannica.com/biography/Charles-Darwin"], [EX, SCI], ["darwin-sails-on-beagle-1831"]),
     "12-27", "additional", ["europe", "global"], ["1800-1945"],
     "Scale of the voyage that began on this day; the options are spaced so only one fits 1831-36."),
    (tf("kepler-elliptical-orbits", "medium",
        "Johannes Kepler's first law states that planets move in circular orbits with the Sun at the center.",
        False,
        "Kepler's first law says planets move in elliptical orbits, with the Sun at one focus of the ellipse.",
        ["https://www.britannica.com/biography/Johannes-Kepler"], [SCI], ["johannes-kepler-born-1571"]),
     "12-27", "additional", ["europe"], ["early-modern"],
     "Targets the common circular-orbit misconception that Kepler overturned."),
    (mc("indonesia-colonial-power", "easy",
        "From which European country did Indonesia win its independence?",
        [("portugal", "Portugal"), ("britain", "Britain"), ("france", "France"), ("netherlands", "The Netherlands")], "netherlands",
        "Indonesia declared independence in 1945, and the Dutch formally relinquished control on December 27, 1949.",
        [U("December", 27)], [EX], ["dutch-transfer-sovereignty-indonesia-1949"]),
     "12-27", "additional", ["asia", "europe"], ["decolonization"],
     "Accessible decolonization hook; Portugal and Britain also held territory in the region."),
    # Dec 28
    (mc("lumiere-first-screening-city", "easy",
        "In which city did the Lumiere brothers first demonstrate their Cinematographe to the public in 1895?",
        [("lyon", "Lyon"), ("paris", "Paris"), ("brussels", "Brussels"), ("london", "London")], "paris",
        "The first public demonstration of the Cinematographe took place at the Grand Cafe in Paris on December 28, 1895.",
        [U("December", 28)], [SCI, S], ["lumiere-first-public-film-screening-1895"]),
     "12-28", "featured", ["europe"], ["1800-1945"],
     "Exact match; Lyon, the brothers' home city, is the deliberate near-miss."),
    (mc("westminster-abbey-founder-king", "medium",
        "Which English king built the abbey church at Westminster that was consecrated in 1065, shortly before his death?",
        [("william-conqueror", "William the Conqueror"), ("harold-ii", "Harold II"),
         ("edward-confessor", "Edward the Confessor"), ("alfred", "Alfred the Great")], "edward-confessor",
        "Edward the Confessor built a new church at Westminster in the Norman style. It was consecrated on December 28, 1065, but Edward was too ill to attend and died about a week later.",
        ["https://www.westminster-abbey.org/abbey-commemorations/royals/edward-the-confessor-and-edith"], [LP], ["westminster-abbey-consecrated-1065"]),
     "12-28", "additional", ["europe"], ["medieval"],
     "William and Harold are the kings of 1066, the natural confusions."),
    (tf("markievicz-took-seat", "medium",
        "Constance Markievicz, the first woman elected to the British House of Commons, took her seat at Westminster.",
        False,
        "Like the other Sinn Fein members elected in 1918, she refused the oath of allegiance and never took her seat. She served instead as minister of labour in the first Dail Eireann.",
        ["https://www.britannica.com/biography/Constance-Markievicz"], [LP, REV], ["constance-markievicz-elected-1918"]),
     "12-28", "additional", ["europe"], ["1800-1945"],
     "The surprising twist behind the milestone."),
    # Dec 29
    (mc("ireland-irish-name", "medium",
        "What is the official Irish-language name of the state of Ireland?",
        [("eire", "Eire"), ("alba", "Alba"), ("cymru", "Cymru"), ("kernow", "Kernow")], "eire",
        "Britannica gives the official name as Eire in Irish and Ireland in English. The constitution that took effect on December 29, 1937, renamed the Irish Free State.",
        ["https://www.britannica.com/place/Ireland", U("December", 29)], [S], ["irish-constitution-in-force-1937"]),
     "12-29", "featured", ["europe"], ["1800-1945"],
     "Distractors are the Celtic names of Scotland, Wales and Cornwall."),
    (mc("texas-before-annexation", "easy",
        "What was Texas immediately before the United States annexed it in 1845?",
        [("spanish-colony", "A Spanish colony"), ("british-dominion", "A British dominion"),
         ("independent-republic", "An independent republic"), ("french-territory", "A French territory")], "independent-republic",
        "Texas was an independent republic. Congress passed the annexation resolution on February 28, 1845, and Texas legally entered the Union as a state on December 29, 1845.",
        ["https://www.tshaonline.org/handbook/entries/annexation", U("December", 29)], [LP], ["texas-statehood-1845"]),
     "12-29", "additional", ["americas"], ["1800-1945"],
     "Asks about status, not the date; Spain is the earlier ruler and a tempting trap."),
    (mc("gladstone-terms-as-pm", "medium",
        "How many times did William Gladstone serve as British prime minister?",
        [("two", "Two"), ("three", "Three"), ("four", "Four"), ("five", "Five")], "four",
        "Gladstone, born in Liverpool on December 29, 1809, led governments in 1868-74, 1880-85, 1886 and 1892-94.",
        [U("December", 29)], [LP], ["william-gladstone-born-1809"]),
     "12-29", "additional", ["europe"], ["1800-1945"],
     "A memorable record; adjacent numbers make it a real recall question."),
    # Dec 30
    (mc("ussr-capital", "easy",
        "Which city was the capital of the Soviet Union when it was established in 1922?",
        [("st-petersburg", "St. Petersburg"), ("kyiv", "Kyiv"), ("minsk", "Minsk"), ("moscow", "Moscow")], "moscow",
        "The Union of Soviet Socialist Republics was established on December 30, 1922, with its capital in Moscow.",
        [U("December", 30)], [LP], ["soviet-union-established-1922"]),
     "12-30", "featured", ["europe", "asia"], ["1800-1945"],
     "St. Petersburg, the imperial capital, is the trap; Kyiv and Minsk were capitals of founding republics."),
    (mc("rizal-noli-me-tangere-target", "medium",
        "Jose Rizal's novel Noli Me Tangere exposed the abuses of which colonial power in the Philippines?",
        [("spain", "Spain"), ("united-states", "The United States"), ("portugal", "Portugal"), ("netherlands", "The Netherlands")], "spain",
        "Britannica calls Noli Me Tangere a passionate exposure of the evils of Spanish rule. Spanish authorities executed Rizal in Manila on December 30, 1896.",
        ["https://www.britannica.com/biography/Jose-Rizal"], [REV], ["jose-rizal-executed-1896"]),
     "12-30", "additional", ["asia"], ["1800-1945"],
     "The United States, the later colonial power, is the main trap."),
    (mc("gadsden-purchase-seller", "easy",
        "From which country did the United States buy land in the 1853 Gadsden Purchase?",
        [("mexico", "Mexico"), ("spain", "Spain"), ("france", "France"), ("britain", "Britain")], "mexico",
        "The Gadsden Purchase, signed December 30, 1853, gave the United States nearly 30,000 square miles of northern Mexican territory.",
        [U("December", 30)], [EX], ["gadsden-purchase-signed-1853"]),
     "12-30", "additional", ["americas"], ["1800-1945"],
     "Other powers that sold or ceded North American land are the distractors."),
    # Dec 31
    (mc("times-square-named-for", "medium",
        "Times Square in New York City takes its name from what?",
        [("clock-tower", "A clock tower in the square"), ("newspaper", "The New York Times newspaper"),
         ("theater", "A theater called the Times"), ("time-zone", "The adoption of standard time zones")], "newspaper",
        "Longacre Square was renamed in 1904 for The New York Times, which opened offices there. The Times began its New Year's Eve ball drop in 1907.",
        ["https://www.britannica.com/place/Times-Square"], [S], ["times-square-ball-drop-1907"]),
     "12-31", "featured", ["americas"], ["1800-1945"],
     "Links the ball drop to the newspaper that started it; the distractors are plausible folk etymologies."),
    (mc("tallest-building-after-taipei-101", "medium",
        "Which building, opened in Dubai in 2010, took the title of world's tallest from Taipei 101?",
        [("petronas", "Petronas Towers"), ("shanghai-tower", "Shanghai Tower"), ("burj-khalifa", "Burj Khalifa"),
         ("one-wtc", "One World Trade Center")], "burj-khalifa",
        "Taipei 101 opened on December 31, 2004, as the world's tallest building at 508 metres. The Burj Khalifa officially opened in Dubai on January 4, 2010.",
        [U("December", 31), U("January", 4)], [SCI], ["taipei-101-opens-2004", "burj-khalifa-opens-2010"]),
     "12-31", "additional", ["asia", "middle-east"], ["contemporary"],
     "Connects two record-setting openings in this batch; the prompt names Dubai so only one option fits."),
    (mc("ottawa-chosen-by", "medium",
        "Who chose Ottawa as the national capital of Canada in 1857?",
        [("john-a-macdonald", "John A. Macdonald"), ("queen-victoria", "Queen Victoria"),
         ("lord-durham", "Lord Durham"), ("samuel-de-champlain", "Samuel de Champlain")], "queen-victoria",
        "Queen Victoria named Ottawa the national capital on December 31, 1857.",
        [U("December", 31)], [LP], ["ottawa-named-capital-of-canada-1857"]),
     "12-31", "additional", ["americas"], ["1800-1945"],
     "Macdonald and Durham are prominent figures of the period; Champlain is a well-known earlier name."),
    # Jan 1
    (mc("euro-founding-members", "medium",
        "How many European Union countries adopted the euro when it was introduced in 1999?",
        [("six", "6"), ("eleven", "11"), ("fifteen", "15"), ("twenty-seven", "27")], "eleven",
        "Eleven EU countries changed to the euro on January 1, 1999. Others, including Bulgaria in 2026, joined later.",
        [U("January", 1)], [EX], ["euro-introduced-1999"]),
     "01-01", "featured", ["europe"], ["contemporary"],
     "Six echoes the original EEC founders; 15 and 27 are later EU sizes."),
    (mc("wto-predecessor", "hard",
        "The World Trade Organization, established in 1995, succeeded which earlier arrangement?",
        [("gatt", "General Agreement on Tariffs and Trade"), ("bretton-woods", "Bretton Woods system"),
         ("oecd", "Organisation for Economic Co-operation and Development"), ("unctad", "UN Conference on Trade and Development")], "gatt",
        "The WTO began operations on January 1, 1995, as successor to the General Agreement on Tariffs and Trade, created in 1947.",
        ["https://www.britannica.com/topic/World-Trade-Organization"], [EX], ["world-trade-organization-established-1995"]),
     "01-01", "additional", ["global"], ["contemporary"],
     "All four are postwar economic institutions; only GATT was replaced by the WTO."),
    (mc("batista-toppled-by", "easy",
        "Whose rebel forces toppled the Cuban dictator Fulgencio Batista in 1959?",
        [("peron", "Juan Peron"), ("pinochet", "Augusto Pinochet"), ("somoza", "Anastasio Somoza"), ("castro", "Fidel Castro")], "castro",
        "Batista fled Cuba on January 1, 1959, after his regime was toppled by rebel forces led by Fidel Castro.",
        [U("January", 1)], [REV], ["batista-flees-cuba-1959"]),
     "01-01", "additional", ["americas"], ["cold-war"],
     "Distractors are other Latin American strongmen, none of them Cuban revolutionaries."),
    (tf("emancipation-proclamation-scope", "medium",
        "The Emancipation Proclamation of January 1, 1863, declared freedom for enslaved people in the states then in rebellion against the Union.",
        True,
        "Lincoln's proclamation applied to enslaved people in the Confederacy, the states in rebellion.",
        [U("January", 1)], [REV, S], ["emancipation-proclamation-issued-1863"]),
     "01-01", "additional", ["americas"], ["1800-1945"],
     "Pairs with the published preliminary-proclamation question; this one states the proclamation's actual scope."),
    (order("order-january-first-milestones", "medium",
           "Put these New Year's Day milestones in order from earliest to latest.",
           [("euro", "Eleven countries adopt the euro"), ("emancipation", "Lincoln issues the Emancipation Proclamation"),
            ("batista", "Batista flees Cuba"), ("haiti", "Haiti declares independence")],
           ["haiti", "emancipation", "batista", "euro"],
           "All four happened on January 1: Haiti's independence in 1804, the Emancipation Proclamation in 1863, Batista's flight in 1959, and the euro in 1999.",
           [U("January", 1)], [REV, S],
           ["haiti-declares-independence-1804", "emancipation-proclamation-issued-1863", "batista-flees-cuba-1959", "euro-introduced-1999"]),
     "01-01", "additional", ["americas", "europe"], ["revolutionary", "contemporary"],
     "Every item is one of the day's events, all cited on Britannica's January 1 page."),
    # Jan 2
    (mc("granada-conquerors", "easy",
        "Which monarchs captured Granada in 1492, completing the Christian conquest of Spain?",
        [("henry-catherine", "Henry VIII and Catherine of Aragon"), ("ferdinand-isabella", "Ferdinand II and Isabella I"),
         ("philip-mary", "Philip II and Mary I"), ("charles-isabella", "Charles V and Isabella of Portugal")], "ferdinand-isabella",
        "Ferdinand II and Isabella I, the first monarchs of a unified Spain, captured Granada on January 2, 1492.",
        [U("January", 2)], [LP, WC], ["granada-surrenders-1492"]),
     "01-02", "featured", ["europe"], ["medieval"],
     "Every distractor is a real royal couple with Spanish ties from the following century."),
    (mc("port-arthur-war-enemy", "easy",
        "Russia surrendered Port Arthur in 1905 during a war against which country?",
        [("china", "China"), ("britain", "Britain"), ("japan", "Japan"), ("ottoman-empire", "The Ottoman Empire")], "japan",
        "Russian forces surrendered Port Arthur, later Lushun in China, to the Japanese on January 2, 1905, in the Russo-Japanese War.",
        [U("January", 2)], [WC], ["port-arthur-surrenders-1905"]),
     "01-02", "additional", ["asia", "europe"], ["1800-1945"],
     "China is the trap because the port lies in China."),
    (mc("stardust-sample", "medium",
        "What did NASA's Stardust spacecraft collect in January 2004?",
        [("solar-wind", "Particles of the solar wind"), ("mars-soil", "Soil from Mars"), ("moon-rock", "Rock from the Moon"),
         ("comet-dust", "Dust from a comet")], "comet-dust",
        "On January 2, 2004, Stardust collected dust grains from the comet Wild 2.",
        [U("January", 2)], [SCI], ["stardust-collects-comet-dust-2004"]),
     "01-02", "additional", ["global"], ["contemporary", "space-age"],
     "Solar-wind particles (NASA's Genesis mission) are the close distractor."),
    # Jan 3
    (mc("tolkien-birth-country", "medium",
        "In which country was J.R.R. Tolkien born?",
        [("england", "England"), ("ireland", "Ireland"), ("south-africa", "South Africa"), ("new-zealand", "New Zealand")], "south-africa",
        "Tolkien was born on January 3, 1892, in Bloemfontein, South Africa, and grew up in England.",
        ["https://www.britannica.com/biography/J-R-R-Tolkien"], [S], ["jrr-tolkien-born-1892"]),
     "01-03", "featured", ["africa", "europe"], ["1800-1945"],
     "Surprising origin; New Zealand is the film-location trap."),
    (mc("fiftieth-state-1959", "medium",
        "Alaska became the 49th US state in January 1959. Which became the 50th later that year?",
        [("puerto-rico", "Puerto Rico"), ("hawaii", "Hawaii"), ("guam", "Guam"), ("arizona", "Arizona")], "hawaii",
        "Alaska joined on January 3, 1959, and Hawaii became the 50th state on August 21, 1959.",
        [U("January", 3), "https://www.britannica.com/place/Hawaii-state"], [LP], ["alaska-becomes-49th-state-1959"]),
     "01-03", "additional", ["americas", "oceania"], ["cold-war"],
     "Puerto Rico and Guam are territories that never became states; Arizona joined in 1912."),
    # Jan 4
    (mc("braille-made-of", "easy",
        "Each braille character is formed from what?",
        [("raised-dots", "Raised dots"), ("raised-lines", "Raised lines"), ("notches", "Notches cut in the page edge"),
         ("textured-squares", "Textured squares")], "raised-dots",
        "Braille characters use one to six raised dots arranged in a six-position cell. Louis Braille, born January 4, 1809, devised the system in 1824.",
        ["https://www.britannica.com/topic/braille-writing-system"], [SCI, S], ["louis-braille-born-1809"]),
     "01-04", "featured", ["europe"], ["1800-1945"],
     "Basic mechanism of the featured inventor's system."),
    (mc("burma-modern-name", "easy",
        "Burma, which gained independence from Britain in 1948, is now officially known as what?",
        [("thailand", "Thailand"), ("myanmar", "Myanmar"), ("cambodia", "Cambodia"), ("sri-lanka", "Sri Lanka")], "myanmar",
        "Burma, today called Myanmar, became independent from Great Britain on January 4, 1948.",
        [U("January", 4)], [EX], ["burma-gains-independence-1948"]),
     "01-04", "additional", ["asia"], ["decolonization"],
     "Sri Lanka (formerly Ceylon) also won independence from Britain in 1948, a strong distractor."),
    # Jan 5
    (mc("waiting-for-godot-author", "medium",
        "Who wrote the play Waiting for Godot?",
        [("ionesco", "Eugene Ionesco"), ("sartre", "Jean-Paul Sartre"), ("beckett", "Samuel Beckett"), ("pinter", "Harold Pinter")], "beckett",
        "The Irish writer Samuel Beckett first published the play in French in 1952; it was first staged in Paris on January 5, 1953.",
        ["https://www.britannica.com/topic/Waiting-for-Godot", U("January", 5)], [S], ["waiting-for-godot-premieres-1953"]),
     "01-05", "featured", ["europe"], ["cold-war"],
     "Distractors are contemporaries in the theater of the absurd and existentialism."),
    (tf("eris-pluto-reclassified", "medium",
        "The discovery of the dwarf planet Eris helped lead astronomers to reclassify Pluto as a dwarf planet.",
        True,
        "Eris was discovered on January 5, 2005. The debate it set off led the International Astronomical Union in 2006 to define planets so that Pluto became a dwarf planet.",
        ["https://science.nasa.gov/dwarf-planets/eris/"], [SCI], ["eris-discovered-2005"]),
     "01-05", "additional", ["global"], ["contemporary"],
     "Why an obscure discovery mattered."),
    (mc("golden-gate-connects", "medium",
        "The Golden Gate Bridge connects San Francisco with which county?",
        [("marin", "Marin"), ("alameda", "Alameda"), ("san-mateo", "San Mateo"), ("sonoma", "Sonoma")], "marin",
        "Construction began on January 5, 1933, on the bridge connecting San Francisco with Marin county.",
        [U("January", 5)], [SCI], ["golden-gate-bridge-construction-begins-1933"]),
     "01-05", "additional", ["americas"], ["1800-1945"],
     "All four are Bay Area counties; Alameda is across the Bay Bridge instead."),
    (mc("ford-five-dollar-day", "easy",
        "In January 1914, Henry Ford raised his workers' basic pay to how much a day?",
        [("one-dollar", "$1.00"), ("two-forty", "$2.40"), ("five-dollars", "$5.00"), ("ten-dollars", "$10.00")], "five-dollars",
        "On January 5, 1914, Ford raised pay from $2.40 to $5.00 a day, roughly doubling it.",
        [U("January", 5)], [S], ["ford-five-dollar-day-1914"]),
     "01-05", "additional", ["americas"], ["1800-1945"],
     "Includes the previous $2.40 wage as the before-and-after trap."),
    # Jan 6
    (mc("four-freedoms-not-included", "medium",
        "Which of these was NOT one of Franklin D. Roosevelt's Four Freedoms?",
        [("speech", "Freedom of speech and expression"), ("worship", "Freedom of worship"),
         ("assembly", "Freedom of assembly"), ("want", "Freedom from want")], "assembly",
        "In his State of the Union message of January 6, 1941, Roosevelt named freedom of speech and expression, freedom of worship, freedom from want, and freedom from fear.",
        ["https://www.britannica.com/topic/Four-Freedoms"], [S, LP], ["four-freedoms-speech-1941"]),
     "01-06", "featured", ["americas", "global"], ["1800-1945"],
     "Freedom of assembly sounds like it belongs, which makes the list memorable."),
    (mc("henry-viii-wives-count", "easy",
        "Anne of Cleves was one of Henry VIII's wives. How many times did Henry marry?",
        [("four", "Four"), ("five", "Five"), ("six", "Six"), ("seven", "Seven")], "six",
        "Henry married Anne of Cleves, the fourth of his six wives, on January 6, 1540.",
        [U("January", 6)], [LP], ["henry-viii-marries-anne-of-cleves-1540"]),
     "01-06", "additional", ["europe"], ["early-modern"],
     "Well-known fact that anchors the lesser-known wedding."),
    # Jan 7
    (mc("marian-anderson-1939-concert", "medium",
        "Barred from Constitution Hall in 1939, Marian Anderson sang instead before 75,000 people at which landmark?",
        [("capitol-steps", "The steps of the US Capitol"), ("lincoln-memorial", "The Lincoln Memorial"),
         ("washington-monument", "The Washington Monument"), ("carnegie-hall", "Carnegie Hall")], "lincoln-memorial",
        "Anderson sang at the Lincoln Memorial on Easter Sunday, April 9, 1939. On January 7, 1955, she became the first Black singer to perform as a member of the Metropolitan Opera.",
        ["https://www.britannica.com/biography/Marian-Anderson"], [S], ["marian-anderson-met-debut-1955"]),
     "01-07", "featured", ["americas"], ["1800-1945", "cold-war"],
     "Her most famous concert, giving context for the featured debut."),
    (mc("phnom-penh-country", "easy",
        "Phnom Penh, taken by Vietnamese forces in January 1979, is the capital of which country?",
        [("laos", "Laos"), ("thailand", "Thailand"), ("vietnam", "Vietnam"), ("cambodia", "Cambodia")], "cambodia",
        "Vietnamese forces took Phnom Penh, Cambodia, on January 7, 1979, removing the Khmer Rouge and Pol Pot from power.",
        [U("January", 7)], [WC], ["vietnamese-forces-take-phnom-penh-1979"]),
     "01-07", "additional", ["asia"], ["cold-war"],
     "Neighboring countries as distractors; Vietnam is the invading power."),
    # Jan 8
    (mc("fourteen-points-association", "medium",
        "Woodrow Wilson's fourteenth point called for a general association of nations. What did it become?",
        [("league", "The League of Nations"), ("un", "The United Nations"), ("nato", "NATO"),
         ("hague-court", "The Permanent Court of Arbitration")], "league",
        "Wilson set out the Fourteen Points on January 8, 1918. The call for a general association of nations became the basis of the League of Nations, established on January 10, 1920.",
        ["https://www.britannica.com/event/Fourteen-Points", U("January", 10)], [WW, LP],
        ["wilson-fourteen-points-1918", "league-of-nations-established-1920"]),
     "01-08", "additional", ["americas", "europe"], ["1800-1945"],
     "Links two events in this batch; the UN is the later successor and the main trap."),
    (mc("hawking-best-seller", "easy",
        "What was the title of Stephen Hawking's best-selling 1988 book?",
        [("cosmos", "Cosmos"), ("brief-history", "A Brief History of Time"), ("selfish-gene", "The Selfish Gene"),
         ("elegant-universe", "The Elegant Universe")], "brief-history",
        "Hawking, born in Oxford on January 8, 1942, published A Brief History of Time: From the Big Bang to Black Holes in 1988.",
        ["https://www.britannica.com/biography/Stephen-Hawking"], [SCI], ["stephen-hawking-born-1942"]),
     "01-08", "additional", ["europe"], ["cold-war"],
     "Distractors are other famous popular-science books by different authors."),
    (mc("elvis-memphis-home", "easy",
        "What is the name of Elvis Presley's Memphis estate, now a major tourist attraction?",
        [("graceland", "Graceland"), ("neverland", "Neverland"), ("monticello", "Monticello"), ("dollywood", "Dollywood")], "graceland",
        "Elvis Presley was born in Tupelo, Mississippi, on January 8, 1935. His Memphis home, Graceland, opened to the public in 1982.",
        ["https://www.britannica.com/biography/Elvis-Presley"], [S], ["elvis-presley-born-1935"]),
     "01-08", "additional", ["americas"], ["1800-1945"],
     "Other famous American estates as distractors."),
    # Jan 9
    (mc("joan-of-arc-byname", "medium",
        "Joan of Arc became known as the Maid of which city, after the victory she led there in 1429?",
        [("orleans", "Orleans"), ("reims", "Reims"), ("rouen", "Rouen"), ("paris", "Paris")], "orleans",
        "Joan's byname comes from the 1429 relief of Orleans. Her trial began in Rouen on January 9, 1431.",
        ["https://www.britannica.com/biography/Saint-Joan-of-Arc"], [WC], ["joan-of-arc-trial-begins-1431"]),
     "01-09", "featured", ["europe"], ["medieval"],
     "Rouen (her trial) and Reims (the coronation she secured) are the near-misses."),
    # Jan 10
    (mc("rubicon-boundary", "hard",
        "In Julius Caesar's time, the Rubicon marked the boundary between Italy and which province?",
        [("sicily", "Sicily"), ("hispania", "Hispania"), ("cisalpine-gaul", "Cisalpine Gaul"), ("macedonia", "Macedonia")], "cisalpine-gaul",
        "The Rubicon was a small stream separating Cisalpine Gaul from Italy. Caesar crossed it in 49 BCE, beginning a civil war.",
        ["https://www.britannica.com/place/Rubicon"], [AR, AH], ["caesar-crosses-rubicon-49bce"]),
     "01-10", "featured", ["europe"], ["ancient"],
     "Explains why the crossing was decisive; all options were Roman provinces."),
    (mc("common-sense-author", "easy",
        "Who wrote Common Sense, the 1776 pamphlet urging American independence?",
        [("jefferson", "Thomas Jefferson"), ("franklin", "Benjamin Franklin"), ("samuel-adams", "Samuel Adams"), ("paine", "Thomas Paine")], "paine",
        "Thomas Paine published Common Sense on January 10, 1776; it sold more than 500,000 copies within a few months.",
        [U("January", 10)], [REV], ["common-sense-published-1776"]),
     "01-10", "additional", ["americas"], ["revolutionary"],
     "Other revolutionary writers as distractors."),
    (mc("first-un-general-assembly-city", "medium",
        "In which city did the first United Nations General Assembly meet in January 1946?",
        [("new-york", "New York"), ("geneva", "Geneva"), ("london", "London"), ("san-francisco", "San Francisco")], "london",
        "The first UN General Assembly met in London on January 10, 1946, before the UN settled in New York.",
        [U("January", 10)], [LP, WW], ["first-un-general-assembly-1946"]),
     "01-10", "additional", ["europe", "global"], ["1945-present"],
     "New York, Geneva and San Francisco are each tied to the UN or League, so recall matters."),
    # Jan 11
    (mc("hillary-everest-partner", "easy",
        "Edmund Hillary first reached the summit of Mount Everest in 1953 with which climber?",
        [("tenzing", "Tenzing Norgay"), ("mallory", "George Mallory"), ("messner", "Reinhold Messner"), ("hunt", "John Hunt")], "tenzing",
        "Hillary, a New Zealander, and Tenzing Norgay reached the summit on May 29, 1953. Hillary died on January 11, 2008.",
        ["https://www.britannica.com/biography/Edmund-Hillary"], [EX], ["edmund-hillary-dies-2008"]),
     "01-11", "additional", ["oceania", "asia"], ["cold-war", "contemporary"],
     "Hunt led the 1953 expedition; Mallory and Messner are other famous Everest names."),
    (tf("earhart-atlantic-before-pacific", "medium",
        "Before her 1935 solo flight from Hawaii to California, Amelia Earhart had already flown solo across the Atlantic.",
        True,
        "Earhart crossed the Atlantic alone on May 20-21, 1932. She left Honolulu on January 11, 1935, and landed in Oakland the next day.",
        ["https://www.britannica.com/biography/Amelia-Earhart"], [EX], ["earhart-hawaii-to-california-1935"]),
     "01-11", "additional", ["americas", "oceania"], ["1800-1945"],
     "Places the Pacific flight in her career."),
    # Jan 12
    (mc("gordy-label-name", "easy",
        "Berry Gordy's Detroit record business, founded in January 1959, became famous under which name?",
        [("stax", "Stax"), ("motown", "Motown"), ("chess", "Chess"), ("atlantic", "Atlantic")], "motown",
        "Gordy launched Tamla Records on January 12, 1959; Britannica dates the founding of Motown in Detroit to January 1959.",
        ["https://www.britannica.com/topic/Motown", U("January", 12)], [S], ["berry-gordy-launches-tamla-records-1959"]),
     "01-12", "featured", ["americas"], ["cold-war"],
     "Other landmark American soul and R&B labels as distractors."),
    # Jan 13
    (mc("jaccuse-defended-officer", "easy",
        "Emile Zola's open letter J'accuse defended which wrongly convicted army officer?",
        [("dreyfus", "Alfred Dreyfus"), ("boulanger", "Georges Boulanger"), ("petain", "Philippe Petain"), ("bazaine", "Francois Bazaine")], "dreyfus",
        "Zola's letter of January 13, 1898, denounced the general staff over the 1894 treason court-martial of Alfred Dreyfus.",
        [U("January", 13)], [S], ["zola-publishes-jaccuse-1898"]),
     "01-13", "featured", ["europe"], ["1800-1945"],
     "Other French generals and officers of the era as distractors."),
    # Jan 14
    (tf("huygens-built-by-nasa", "medium",
        "The Huygens probe that landed on Saturn's moon Titan in 2005 was built by NASA.",
        False,
        "Huygens was the European Space Agency's probe. It rode to Saturn aboard NASA's Cassini spacecraft and landed on Titan on January 14, 2005.",
        ["https://science.nasa.gov/mission/cassini/spacecraft/huygens-probe/"], [SCI], ["huygens-lands-on-titan-2005"]),
     "01-14", "featured", ["europe", "global"], ["contemporary", "space-age"],
     "Corrects a common assumption about the landing; complements the published Titan question."),
    (mc("tosca-composer", "easy",
        "Who composed the opera Tosca, first performed in Rome in 1900?",
        [("verdi", "Giuseppe Verdi"), ("rossini", "Gioachino Rossini"), ("puccini", "Giacomo Puccini"), ("bizet", "Georges Bizet")], "puccini",
        "Puccini's Tosca premiered at Rome's Costanzi Theatre on January 14, 1900.",
        [U("January", 14)], [S], ["tosca-premieres-1900"]),
     "01-14", "additional", ["europe"], ["1800-1945"],
     "Other great opera composers as distractors."),
    (mc("jasmine-revolution-wave", "medium",
        "Tunisia's 2011 uprising, which drove President Ben Ali from power, inspired which wave of protests?",
        [("arab-spring", "The Arab Spring"), ("color-revolutions", "The Color Revolutions"), ("velvet", "The Velvet Revolution"),
         ("cedar", "The Cedar Revolution")], "arab-spring",
        "Ben Ali stepped down and left Tunisia on January 14, 2011. The uprising inspired the protests across the Middle East and North Africa known as the Arab Spring.",
        ["https://www.britannica.com/event/Jasmine-Revolution"], [REV], ["ben-ali-steps-down-2011"]),
     "01-14", "additional", ["africa", "middle-east"], ["contemporary"],
     "Distractors are other named protest movements, including Lebanon's earlier Cedar Revolution."),
    # Jan 15
    (mc("british-museum-first-home", "hard",
        "When the British Museum opened in 1759, its collections were displayed in which London mansion?",
        [("somerset-house", "Somerset House"), ("montagu-house", "Montagu House"), ("burlington-house", "Burlington House"),
         ("marlborough-house", "Marlborough House")], "montagu-house",
        "Founded by act of Parliament in 1753 and opened on January 15, 1759, the museum housed its collections in Montagu House on Great Russell Street.",
        ["https://www.britannica.com/topic/British-Museum"], [S], ["british-museum-opens-1759"]),
     "01-15", "featured", ["europe"], ["early-modern"],
     "Hard: all four are historic London mansions with institutional uses."),
    # Jan 16
    (mc("first-american-woman-in-space", "easy",
        "Which member of NASA's 1978 astronaut class became the first American woman in space?",
        [("sally-ride", "Sally Ride"), ("mae-jemison", "Mae Jemison"), ("eileen-collins", "Eileen Collins"), ("christa-mcauliffe", "Christa McAuliffe")], "sally-ride",
        "Ride was one of six women in the class announced on January 16, 1978. She flew on Challenger on June 18, 1983.",
        ["https://www.britannica.com/biography/Sally-Ride"], [SCI], ["nasa-selects-first-women-astronauts-1978"]),
     "01-16", "additional", ["americas"], ["space-age", "cold-war"],
     "Other notable American women in spaceflight history as distractors."),
    # Jan 17
    (mc("popeye-strength-food", "easy",
        "Popeye the Sailor famously gets his strength from eating what?",
        [("carrots", "Carrots"), ("spinach", "Spinach"), ("broccoli", "Broccoli"), ("sardines", "Sardines")], "spinach",
        "Popeye, known for his love of spinach, first appeared in the comic strip Thimble Theatre on January 17, 1929.",
        [U("January", 17)], [S], ["popeye-debuts-1929"]),
     "01-17", "featured", ["americas"], ["1800-1945"],
     "A light, accessible hook for the featured debut."),
    (mc("franklin-birth-city", "easy",
        "In which city was Benjamin Franklin born?",
        [("philadelphia", "Philadelphia"), ("new-york", "New York"), ("baltimore", "Baltimore"), ("boston", "Boston")], "boston",
        "Franklin was born in Boston on January 17, 1706 (January 6 in the Old Style calendar). He later made his name in Philadelphia.",
        ["https://www.britannica.com/biography/Benjamin-Franklin"], [LP], ["benjamin-franklin-born-1706"]),
     "01-17", "additional", ["americas"], ["early-modern"],
     "Philadelphia, his adopted home, is the trap."),
    # Jan 18
    (mc("german-empire-proclaimed-where", "medium",
        "In January 1871, William I was acclaimed German emperor in which French town, then occupied by Prussian forces?",
        [("versailles", "Versailles"), ("sedan", "Sedan"), ("strasbourg", "Strasbourg"), ("fontainebleau", "Fontainebleau")], "versailles",
        "William I was acclaimed German emperor at Versailles, in conquered France, on January 18, 1871.",
        ["https://www.britannica.com/biography/William-I-emperor-of-Germany"], [LP, WC], ["german-empire-proclaimed-1871"]),
     "01-18", "featured", ["europe"], ["1800-1945"],
     "Sedan (the decisive 1870 battle) and Strasbourg (annexed in 1871) are the close distractors."),
    # Jan 19
    (mc("poe-genre-pioneered", "medium",
        "Edgar Allan Poe's 'The Murders in the Rue Morgue' (1841) is credited with pioneering which genre?",
        [("western", "The Western"), ("detective", "The detective story"), ("historical", "The historical novel"),
         ("epistolary", "The epistolary novel")], "detective",
        "Poe, born in Boston on January 19, 1809, pioneered the modern detective story with 'The Murders in the Rue Morgue'.",
        ["https://www.britannica.com/biography/Edgar-Allan-Poe"], [S], ["edgar-allan-poe-born-1809"]),
     "01-19", "additional", ["americas"], ["1800-1945"],
     "Distractors are established genres Poe did not originate."),
    # Jan 20
    (mc("obama-senate-state", "easy",
        "Before becoming president, Barack Obama served as a US senator from which state?",
        [("hawaii", "Hawaii"), ("illinois", "Illinois"), ("new-york", "New York"), ("massachusetts", "Massachusetts")], "illinois",
        "Obama represented Illinois in the Senate from 2005 to 2008 and was inaugurated president on January 20, 2009.",
        ["https://www.britannica.com/biography/Barack-Obama"], [LP], ["obama-inaugurated-2009"]),
     "01-20", "featured", ["americas"], ["contemporary"],
     "Hawaii, his birthplace, is the trap."),
    # Jan 21
    (mc("concorde-partner-country", "easy",
        "Concorde was built with funding from the British government and the government of which other country?",
        [("germany", "West Germany"), ("italy", "Italy"), ("united-states", "The United States"), ("france", "France")], "france",
        "Concorde, funded by the British and French governments, began regular commercial service on January 21, 1976.",
        [U("January", 21)], [SCI], ["concorde-begins-service-1976"]),
     "01-21", "featured", ["europe"], ["cold-war"],
     "Other aerospace nations of the era as distractors."),
    (mc("louis-xvi-queen", "easy",
        "Louis XVI was executed in January 1793. Which queen, his wife, was guillotined later that year?",
        [("marie-antoinette", "Marie-Antoinette"), ("josephine", "Josephine"), ("catherine-de-medici", "Catherine de Medici"),
         ("marie-louise", "Marie-Louise")], "marie-antoinette",
        "Louis XVI was guillotined on January 21, 1793. Marie-Antoinette, his queen consort, was guillotined on October 16, 1793.",
        ["https://www.britannica.com/biography/Marie-Antoinette-queen-of-France", U("January", 21)], [REV], ["louis-xvi-executed-1793"]),
     "01-21", "additional", ["europe"], ["revolutionary"],
     "Napoleon's two empresses and an earlier queen as distractors."),
    (mc("petrograd-renamed-1924", "medium",
        "After Lenin's death in January 1924, the city of Petrograd was renamed what?",
        [("stalingrad", "Stalingrad"), ("leningrad", "Leningrad"), ("kaliningrad", "Kaliningrad"), ("volgograd", "Volgograd")], "leningrad",
        "Petrograd was called Leningrad from 1924 to 1991, when it became St. Petersburg again.",
        ["https://www.britannica.com/place/Saint-Petersburg-Russia"], [REV, LP], ["lenin-dies-1924", "siege-of-leningrad-ends-1944"]),
     "01-21", "additional", ["europe"], ["1800-1945"],
     "Links Lenin's death to the Leningrad siege event; the other Soviet-era city names are the distractors."),
    # Jan 22
    (mc("victoria-successor", "medium",
        "Who succeeded Queen Victoria on the British throne when she died in 1901?",
        [("george-v", "George V"), ("edward-vii", "Edward VII"), ("albert", "Prince Albert"), ("william-iv", "William IV")], "edward-vii",
        "Victoria died on January 22, 1901, after reigning from 1837, and was succeeded by her son Edward VII.",
        ["https://www.britannica.com/biography/Victoria-queen-of-United-Kingdom"], [LP], ["queen-victoria-dies-1901"]),
     "01-22", "featured", ["europe"], ["1800-1945"],
     "William IV was her predecessor, Albert her late husband, George V her grandson."),
    # Jan 23
    (mc("blackwell-birth-country", "hard",
        "Elizabeth Blackwell, the first woman to graduate from medical school in the United States, was born in which country?",
        [("united-states", "The United States"), ("ireland", "Ireland"), ("england", "England"), ("canada", "Canada")], "england",
        "Blackwell was born in Bristol, England, in 1821 and graduated from Geneva Medical College, New York, in January 1849.",
        ["https://www.britannica.com/biography/Elizabeth-Blackwell"], [SCI, S], ["elizabeth-blackwell-md-1849"]),
     "01-23", "featured", ["americas", "europe"], ["1800-1945"],
     "A surprising origin for an American first."),
    # Jan 24
    (mc("gold-rush-mill-owner", "medium",
        "California's gold was first found in 1848 at a sawmill belonging to which settler?",
        [("john-sutter", "John Sutter"), ("levi-strauss", "Levi Strauss"), ("john-fremont", "John C. Fremont"),
         ("kit-carson", "Kit Carson")], "john-sutter",
        "On January 24, 1848, James Marshall found gold at Sutter's Mill on the American River at Coloma.",
        ["https://www.britannica.com/topic/California-Gold-Rush"], [EX], ["gold-discovered-california-1848"]),
     "01-24", "featured", ["americas"], ["1800-1945"],
     "Other famous figures of the Gold Rush era as distractors."),
    (mc("macintosh-ad-novel", "medium",
        "Apple's Super Bowl advertisement for the Macintosh in January 1984 was inspired by which novel?",
        [("brave-new-world", "Brave New World"), ("fahrenheit-451", "Fahrenheit 451"), ("nineteen-eighty-four", "Nineteen Eighty-Four"),
         ("animal-farm", "Animal Farm")], "nineteen-eighty-four",
        "The commercial aired on January 22, 1984, two days before Steve Jobs introduced the Macintosh on January 24.",
        [U("January", 22), U("January", 24)], [SCI], ["apple-introduces-macintosh-1984"]),
     "01-24", "additional", ["americas"], ["cold-war"],
     "Other dystopian classics as distractors, including Orwell's own Animal Farm."),
    # Jan 25
    (mc("first-winter-olympics-country", "easy",
        "The first Winter Olympic Games were held in 1924 in which country?",
        [("switzerland", "Switzerland"), ("norway", "Norway"), ("france", "France"), ("austria", "Austria")], "france",
        "The first Winter Olympics were held at Chamonix, France, from January 25 to February 5, 1924.",
        ["https://www.britannica.com/event/Chamonix-1924-Olympic-Winter-Games"], [S], ["first-winter-olympics-open-1924"]),
     "01-25", "featured", ["europe"], ["1800-1945"],
     "Other Alpine and Nordic winter-sport nations as distractors."),
    (tf("sonja-henie-chamonix", "hard",
        "Sonja Henie, later a three-time Olympic figure skating champion, won a medal at the first Winter Olympics in 1924.",
        False,
        "Henie made her Olympic debut at Chamonix at age 11 and finished last in the standings.",
        ["https://www.britannica.com/event/Chamonix-1924-Olympic-Winter-Games"], [S], ["first-winter-olympics-open-1924"]),
     "01-25", "featured", ["europe"], ["1800-1945"],
     "A memorable detail from the featured Games."),
    (mc("burns-new-year-song", "easy",
        "Which song, sung at New Year around the world, is associated with Robert Burns?",
        [("auld-lang-syne", "Auld Lang Syne"), ("greensleeves", "Greensleeves"), ("danny-boy", "Danny Boy"),
         ("scotland-the-brave", "Scotland the Brave")], "auld-lang-syne",
        "Burns, born on January 25, 1759, in Alloway, Scotland, contributed to more than 300 songs, among them 'Auld Lang Syne'.",
        ["https://www.britannica.com/biography/Robert-Burns"], [S], ["robert-burns-born-1759"]),
     "01-25", "additional", ["europe"], ["early-modern"],
     "Other well-known British Isles songs as distractors."),
    (mc("woolf-literary-circle", "medium",
        "Virginia Woolf was at the center of which circle of London writers and thinkers?",
        [("inklings", "The Inklings"), ("bloomsbury", "The Bloomsbury group"), ("lost-generation", "The Lost Generation"),
         ("algonquin", "The Algonquin Round Table")], "bloomsbury",
        "Woolf, born in London on January 25, 1882, hosted gatherings that became known as the Bloomsbury group.",
        ["https://www.britannica.com/biography/Virginia-Woolf"], [S], ["virginia-woolf-born-1882"]),
     "01-25", "additional", ["europe"], ["1800-1945"],
     "Other famous literary circles from Oxford, Paris and New York."),
    # Jan 26
    (mc("cullinan-presented-to", "medium",
        "To which British monarch was the Cullinan diamond presented in 1907?",
        [("victoria", "Queen Victoria"), ("george-v", "George V"), ("edward-vii", "Edward VII"), ("george-vi", "George VI")], "edward-vii",
        "Found on January 26, 1905, the diamond was presented to Edward VII. Its largest cut stones are set in the Sovereign's Sceptre and the Imperial Crown.",
        ["https://www.britannica.com/topic/Cullinan-diamond", U("January", 26)], [LP], ["cullinan-diamond-found-1905"]),
     "01-26", "featured", ["africa", "europe"], ["1800-1945"],
     "Victoria had died in 1901; George V and VI reigned later."),
    # Jan 27
    (mc("mozart-opera", "easy",
        "Which of these operas did Wolfgang Amadeus Mozart compose?",
        [("carmen", "Carmen"), ("la-traviata", "La Traviata"), ("fidelio", "Fidelio"), ("magic-flute", "The Magic Flute")], "magic-flute",
        "Mozart, born in Salzburg on January 27, 1756, wrote The Marriage of Figaro, Don Giovanni and The Magic Flute.",
        ["https://www.britannica.com/biography/Wolfgang-Amadeus-Mozart"], [S], ["mozart-born-1756"]),
     "01-27", "featured", ["europe"], ["early-modern"],
     "Famous operas by Bizet, Verdi and Beethoven as distractors."),
    (tf("auschwitz-location", "medium",
        "The Auschwitz camp, liberated by Soviet troops in January 1945, was located in what is now Poland.",
        True,
        "Auschwitz lay near Oswiecim in southern Poland, in territory Germany had annexed. Soviet troops arrived on January 27, 1945.",
        ["https://www.britannica.com/place/Auschwitz"], [WW], ["auschwitz-liberated-1945"]),
     "01-27", "additional", ["europe"], ["1800-1945"],
     "Factual and restrained; corrects the assumption that the camp was in Germany."),
    # Jan 28
    (mc("lego-home-country", "easy",
        "The LEGO company, which patented its interlocking brick in 1958, is based in which country?",
        [("sweden", "Sweden"), ("denmark", "Denmark"), ("germany", "Germany"), ("netherlands", "The Netherlands")], "denmark",
        "LEGO is based in Billund, Denmark; its name comes from the Danish leg godt, 'play well'. The brick patent was filed on January 28, 1958.",
        ["https://www.britannica.com/topic/LEGO"], [SCI, S], ["lego-brick-patent-1958"]),
     "01-28", "featured", ["europe"], ["cold-war"],
     "Sweden is the Scandinavian trap."),
    (mc("challenger-teacher", "medium",
        "Which teacher was among the seven crew members lost aboard Challenger in 1986?",
        [("sally-ride", "Sally Ride"), ("christa-mcauliffe", "Christa McAuliffe"), ("barbara-morgan", "Barbara Morgan"),
         ("judith-resnik", "Judith Resnik")], "christa-mcauliffe",
        "Christa McAuliffe was to teach lessons from orbit. Challenger broke apart 73 seconds after liftoff on January 28, 1986.",
        ["https://www.britannica.com/event/Challenger-disaster"], [SCI], ["challenger-disaster-1986"]),
     "01-28", "additional", ["americas"], ["space-age", "cold-war"],
     "Judith Resnik was a mission specialist on the same flight, so the question asks specifically for the teacher; Morgan was McAuliffe's backup."),
    (mc("pride-prejudice-heroine", "easy",
        "Who is the heroine of Jane Austen's Pride and Prejudice?",
        [("emma-woodhouse", "Emma Woodhouse"), ("anne-elliot", "Anne Elliot"), ("elizabeth-bennet", "Elizabeth Bennet"),
         ("elinor-dashwood", "Elinor Dashwood")], "elizabeth-bennet",
        "Pride and Prejudice, published on January 28, 1813, follows Elizabeth Bennet and Fitzwilliam Darcy.",
        ["https://www.britannica.com/topic/Pride-and-Prejudice"], [S], ["pride-and-prejudice-published-1813"]),
     "01-28", "additional", ["europe"], ["1800-1945"],
     "Heroines of other Austen novels as distractors."),
    # Jan 29
    (mc("benz-motorwagen-wheels", "medium",
        "How many wheels did Karl Benz's patented Motorwagen of 1886 have?",
        [("two", "Two"), ("three", "Three"), ("four", "Four"), ("six", "Six")], "three",
        "Benz's Motorwagen was a three-wheeled, internal-combustion vehicle, patented on January 29, 1886.",
        ["https://www.britannica.com/biography/Karl-Benz"], [SCI], ["benz-patents-automobile-1886"]),
     "01-29", "featured", ["europe"], ["1800-1945"],
     "Most people assume four; a vivid fact about the first car."),
    (mc("chekhov-play", "medium",
        "Which of these plays did Anton Chekhov write?",
        [("dolls-house", "A Doll's House"), ("cherry-orchard", "The Cherry Orchard"), ("miss-julie", "Miss Julie"),
         ("lower-depths", "The Lower Depths")], "cherry-orchard",
        "Chekhov, born in Taganrog on January 29, 1860, wrote The Seagull, Uncle Vanya, Three Sisters and The Cherry Orchard.",
        ["https://www.britannica.com/biography/Anton-Chekhov"], [S], ["anton-chekhov-born-1860"]),
     "01-29", "additional", ["europe"], ["1800-1945"],
     "Plays by Ibsen, Strindberg and Gorky, his contemporaries."),
    # Jan 30
    (mc("gandhi-1930-march-tax", "easy",
        "Gandhi's 1930 march to the sea at Dandi protested a British tax on what?",
        [("tea", "Tea"), ("cotton", "Cotton"), ("salt", "Salt"), ("land", "Land")], "salt",
        "The 1930 march from Sabarmati Ashram to Dandi challenged the British salt tax. Gandhi was assassinated on January 30, 1948.",
        ["https://www.britannica.com/event/Salt-March"], [REV], ["gandhi-assassinated-1948"]),
     "01-30", "additional", ["asia"], ["decolonization", "1800-1945"],
     "Remembers Gandhi through his most famous campaign rather than his death."),
    # Jan 31
    (mc("brexit-referendum-year", "easy",
        "The United Kingdom left the European Union on January 31, 2020. In which year did it vote to leave?",
        [("2014", "2014"), ("2016", "2016"), ("2018", "2018"), ("2019", "2019")], "2016",
        "About 52 percent of voters chose to leave in the referendum of June 23, 2016.",
        ["https://www.britannica.com/topic/Brexit"], [LP], ["uk-leaves-european-union-2020"]),
     "01-31", "featured", ["europe"], ["contemporary"],
     "Close neighboring years as distractors."),
    (mc("schubert-unfinished", "medium",
        "Franz Schubert's Symphony in B minor is known by what nickname?",
        [("unfinished", "Unfinished"), ("pastoral", "Pastoral"), ("surprise", "Surprise"), ("jupiter", "Jupiter")], "unfinished",
        "Schubert, born near Vienna on January 31, 1797, wrote the Unfinished Symphony in 1822.",
        ["https://www.britannica.com/biography/Franz-Schubert"], [S], ["franz-schubert-born-1797"]),
     "01-31", "additional", ["europe"], ["revolutionary", "1800-1945"],
     "Nicknames of symphonies by Beethoven, Haydn and Mozart."),
    (mc("jackie-robinson-team", "easy",
        "With which team did Jackie Robinson break Major League Baseball's color line in 1947?",
        [("yankees", "New York Yankees"), ("giants", "New York Giants"), ("red-sox", "Boston Red Sox"), ("dodgers", "Brooklyn Dodgers")], "dodgers",
        "Robinson, born in Cairo, Georgia, on January 31, 1919, debuted with the Brooklyn Dodgers on April 15, 1947.",
        ["https://www.britannica.com/biography/Jackie-Robinson"], [S], ["jackie-robinson-born-1919"]),
     "01-31", "additional", ["americas"], ["1800-1945", "cold-war"],
     "Other storied teams of the era."),
    (mc("stalingrad-modern-name", "medium",
        "The city of Stalingrad, where Friedrich Paulus surrendered in January 1943, is now called what?",
        [("volgograd", "Volgograd"), ("leningrad", "Leningrad"), ("kaliningrad", "Kaliningrad"), ("donetsk", "Donetsk")], "volgograd",
        "Paulus agreed to give himself up on January 31, 1943, in Stalingrad, now Volgograd, on the Volga.",
        ["https://www.britannica.com/event/Battle-of-Stalingrad"], [WW], ["paulus-surrenders-at-stalingrad-1943"]),
     "01-31", "additional", ["europe"], ["1800-1945"],
     "Donetsk was also once named Stalino; Leningrad and Kaliningrad are other Soviet-era names."),
    # Cross-day ordering questions
    (order("order-space-milestones-dec-jan", "medium",
           "Put these space milestones in order from earliest to latest.",
           [("huygens", "Huygens lands on Titan"), ("change-4", "Chang'e 4 lands on the Moon's far side"),
            ("surveyor-7", "Surveyor 7 launches toward the Moon"), ("challenger", "Space shuttle Challenger is lost")],
           ["surveyor-7", "challenger", "huygens", "change-4"],
           "Surveyor 7 launched in 1968, Challenger was lost in 1986, Huygens landed on Titan in 2005, and Chang'e 4 reached the lunar far side in 2019.",
           [U("January", 7), U("January", 28), U("January", 14), U("January", 3)], [SCI],
           ["surveyor-7-launched-1968", "challenger-disaster-1986", "huygens-lands-on-titan-2005", "change-4-lands-far-side-moon-2019"]),
     "01-07", "additional", ["global"], ["space-age", "contemporary"],
     "Every item is an event in this batch, each dated on its Britannica day page."),
    (order("order-writer-births-january", "medium",
           "Put the births of these writers in order from earliest to latest.",
           [("tolkien", "J.R.R. Tolkien"), ("poe", "Edgar Allan Poe"), ("byron", "Lord Byron"), ("chekhov", "Anton Chekhov")],
           ["byron", "poe", "chekhov", "tolkien"],
           "Byron was born in 1788, Poe in 1809, Chekhov in 1860 and Tolkien in 1892, all in January.",
           [U("January", 22), U("January", 19), U("January", 29), U("January", 3)], [S],
           ["lord-byron-born-1788", "edgar-allan-poe-born-1809", "anton-chekhov-born-1860", "jrr-tolkien-born-1892"]),
     "01-22", "additional", ["europe", "americas"], ["1800-1945"],
     "Every item is a birth in this batch."),
]

# Balance correct-option positions: these questions list their answer first above for readability;
# it is moved to the last position in the written drafts.
CORRECT_LAST = {"ireland-irish-name", "gadsden-purchase-seller", "wto-predecessor", "golden-gate-connects",
                "hillary-everest-partner", "jasmine-revolution-wave", "burns-new-year-song"}
for _q, *_ in NEW:
    if _q["id"] in CORRECT_LAST:
        assert _q["options"][0]["id"] == _q["correctOptionId"], _q["id"]
        _q["options"].append(_q["options"].pop(0))

# (existing question, event, calendarDay, role, regions, eras, sources, rationale, image-rights evidence)
LINKS = [
    ("identify-ada-lovelace", "charles-babbage-born-1791", "12-26", "additional", ["europe"], ["1800-1945"],
     ["https://www.britannica.com/biography/Ada-Lovelace", "https://www.britannica.com/biography/Charles-Babbage"],
     "The explanation describes Lovelace's 1843 notes on Babbage's Analytical Engine; Britannica's Babbage article covers the same notes.",
     "editorial/batches/2026-09-l7-image-identification/review-ledger.json"),
    ("identify-hagia-sophia", "hagia-sophia-consecrated-537", "12-27", "featured", ["europe", "middle-east"], ["medieval"],
     ["https://www.britannica.com/topic/Hagia-Sophia"],
     "Exact match: the image question identifies the monument completed in 537, the year of the featured consecration.",
     "editorial/batches/2026-09-l7-image-identification/review-ledger.json"),
    ("identify-charles-darwin", "darwin-sails-on-beagle-1831", "12-27", "additional", ["europe", "global"], ["1800-1945"],
     ["https://www.britannica.com/biography/Charles-Darwin"],
     "Already related to the Beagle's return (1836); the departure is the start of the same voyage.",
     "editorial/batches/2026-09-l7-second-accessible-global-history/review-ledger.json"),
    ("identify-jose-rizal", "jose-rizal-executed-1896", "12-30", "additional", ["asia"], ["1800-1945"],
     ["https://nhcp.gov.ph/jose-rizal/", "https://www.britannica.com/biography/Jose-Rizal"],
     "The portrait identifies the reformer whose execution the event describes.",
     "editorial/batches/2026-09-l7-second-accessible-global-history/review-ledger.json"),
    ("amundsen-first-south-pole", "scott-sets-farthest-south-record-1902", "12-30", "additional", ["antarctica", "europe"], ["1800-1945"],
     ["https://www.britannica.com/on-this-day/December-14", U("December", 30)],
     "Scott's 1902 farthest-south record was a step in the race for the pole that Amundsen won in 1911.", None),
    ("panama-canal-transfer-year", "panama-canal-handed-to-panama-1999", "12-31", "additional", ["americas"], ["contemporary"],
     ["https://pancanal.com/en/history-of-the-panama-canal/", U("December", 31)],
     "Exact match. The event names the year, so reading the story first reveals the answer; that is learning, not leakage in the quiz itself.", None),
    ("haitian-revolution-outcome", "haiti-declares-independence-1804", "01-01", "additional", ["americas"], ["revolutionary"],
     ["https://www.britannica.com/topic/Haitian-Revolution", U("January", 1)],
     "Exact match: the question asks which country declared independence after the revolution in Saint-Domingue.", None),
    ("alhambra-nasrid-palace", "granada-surrenders-1492", "01-02", "featured", ["europe"], ["medieval"],
     ["https://whc.unesco.org/en/list/314", U("January", 2)],
     "The Nasrid dynasty that built the Alhambra ruled the kingdom of Granada that Ferdinand and Isabella captured.", None),
    ("south-africa-1994-president", "african-national-congress-founded-1912", "01-08", "featured", ["africa"], ["1800-1945"],
     ["https://www.nelsonmandela.org/biography", U("January", 8)],
     "The explanation names the ANC's 1994 election victory, the outcome of the movement founded in 1912.", None),
    ("versailles-league-created", "league-of-nations-established-1920", "01-10", "additional", ["europe", "global"], ["1800-1945"],
     ["https://history.state.gov/milestones/1914-1920/paris-peace", U("January", 10)],
     "Exact match: the question asks which body emerged from the peace conference; the event is its establishment.", None),
    ("united-states-league-member", "league-of-nations-established-1920", "01-10", "additional", ["americas", "europe"], ["1800-1945"],
     ["https://history.state.gov/milestones/1914-1920/league", U("January", 10)],
     "A well-known misconception about the League founded on this day.", None),
    ("huygens-titan-landing", "huygens-lands-on-titan-2005", "01-14", "featured", ["europe", "global"], ["contemporary", "space-age"],
     ["https://science.nasa.gov/mission/cassini/spacecraft/huygens-probe/"],
     "Exact match: the explanation states the January 14, 2005 landing. Already related to Cassini's launch.", None),
    ("identify-queen-liliuokalani", "liliuokalani-deposed-1893", "01-17", "additional", ["oceania", "americas"], ["1800-1945"],
     ["https://www.loc.gov/pictures/item/2016651074/", U("January", 17)],
     "The portrait identifies the last reigning Hawaiian monarch, deposed on this day.",
     "editorial/batches/2026-09-l7-accessible-global-history/review-ledger.json"),
    ("identify-winston-churchill", "winston-churchill-dies-1965", "01-24", "additional", ["europe"], ["cold-war"],
     ["https://www.britannica.com/biography/Winston-Churchill"],
     "The portrait identifies the wartime prime minister whose death the event marks.",
     "docs/QUIZ_CONTENT_REVIEW.md (Q7 image-rights table)"),
    ("india-independence-1947", "india-becomes-republic-1950", "01-26", "additional", ["asia"], ["decolonization"],
     ["https://www.britannica.com/topic/Indian-Independence-Act-1947", U("January", 26)],
     "Independence in 1947 preceded the 1950 republic; together they mark the end of British rule.", None),
    ("mozart-death-age", "mozart-born-1756", "01-27", "featured", ["europe"], ["early-modern"],
     ["https://www.britannica.com/on-this-day/December-5", "https://www.britannica.com/biography/Wolfgang-Amadeus-Mozart"],
     "Mozart's age at death (35) follows from his birth on this day in 1756.", None),
    ("discovery-sts26-return-to-flight", "challenger-disaster-1986", "01-28", "additional", ["americas"], ["space-age", "cold-war"],
     ["https://www.nasa.gov/history/SP-4219/Chapter15.html", U("January", 28)],
     "The question is about the return to flight after the Challenger loss; already related to that 1988 flight.", None),
    ("identify-mahatma-gandhi", "gandhi-assassinated-1948", "01-30", "additional", ["asia"], ["decolonization"],
     ["https://www.britannica.com/biography/Mahatma-Gandhi"],
     "The portrait identifies Gandhi; already related to his birth.",
     "docs/QUIZ_CONTENT_REVIEW.md (Q7 image-rights table)"),
    ("beatles-home-city", "beatles-rooftop-concert-1969", "01-30", "featured", ["europe"], ["cold-war"],
     ["https://www.thebeatles.com/please-please-me", U("January", 30)],
     "Accessible Beatles hook for their last live performance; already related to Love Me Do.", None),
]

def canonical_questions():
    found = {}
    for path in sorted(glob.glob("content/quizzes/questions/*.json")):
        for q in json.load(open(path))["questions"]:
            found[q["id"]] = (path, q)
    return found


def write(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")


def check(url):
    return {"url": url, "status": "verified_supporting", "checkedOn": CHECKED, "note": SRC[url][1]}


def answer_text(q):
    if q["type"] == "chronological_ordering":
        items = {i["id"]: i["text"] for i in q["items"]}
        return " < ".join(items[i] for i in q["correctOrderItemIds"])
    return next(o["text"] for o in q["options"] if o["id"] == q["correctOptionId"])


def build(bank, events):
    out = f"editorial/batches/{BATCH_ID}"
    candidates, entries, link_records = [], [], []
    for q, day, role, regions, eras, rel in NEW:
        assert q["id"] not in bank, q["id"]
        assert all(r in events for r in q["relatedEventIds"]), q["id"]
        urls = [s["url"] for s in q["sources"]]
        candidates.append({"candidateId": q["id"], "kind": "quiz", "proposedCanonicalId": q["id"],
                           "workingClaim": f"{q['prompt']} Answer: {answer_text(q)}. Proposed {role} link on {day}: {', '.join(q['relatedEventIds'])}. {rel}",
                           "sourceUrls": urls})
        entries.append({"candidateId": q["id"], "canonicalId": q["id"], "reviewStatus": "source_verified",
                        "sourceChecks": [check(u) for u in urls], "imageRightsStatus": "not_applicable",
                        "regions": regions, "eras": eras, "calendarDays": [day],
                        "notes": NOTE_NEW.format(rel=rel)})
    for qid, event_id, day, role, regions, eras, urls, rel, rights in LINKS:
        path, q = bank[qid]
        assert q["publicationState"] == "published", qid
        assert event_id in events, event_id
        assert event_id not in (q.get("relatedEventIds") or []), qid
        snapshot = hashlib.sha256(json.dumps(q, separators=(",", ":")).encode()).hexdigest()
        link_records.append({"questionId": qid, "canonicalPack": path, "canonicalSnapshotSha256": snapshot,
                             "currentRelatedEventIds": q.get("relatedEventIds") or [],
                             "addRelatedEventIds": [event_id], "calendarDay": day, "eventRole": role,
                             "relationshipRationale": rel,
                             "existingImageRightsEvidence": rights})
        candidates.append({"candidateId": f"link-{qid}", "kind": "quiz", "proposedCanonicalId": qid,
                           "workingClaim": f"Propose {role} relation on {day} from unchanged published {qid} to {event_id}. {rel}",
                           "sourceUrls": urls})
        extra = (f"Image rights inherited from {rights}; owned URL and provenance unchanged, no new download."
                 if rights else "No image.")
        entries.append({"candidateId": f"link-{qid}", "canonicalId": qid, "reviewStatus": "source_verified",
                        "sourceChecks": [check(u) for u in urls],
                        "imageRightsStatus": "verified" if rights else "not_applicable",
                        "regions": regions, "eras": eras, "calendarDays": [day],
                        "notes": NOTE_LINK.format(extra=extra)})
    write(f"{out}/batch.json", {"schemaVersion": 1, "batchId": BATCH_ID, "candidateFile": "candidates.json",
                                "reviewLedgerFile": "review-ledger.json", "eventIds": [], "monthDays": [],
                                "quizPackFilenames": [PACK]})
    write(f"{out}/candidates.json", {"schemaVersion": 1, "batchId": BATCH_ID, "candidates": candidates})
    write(f"{out}/review-ledger.json", {"schemaVersion": 1, "batchId": BATCH_ID, "entries": entries})
    write(f"{out}/draft-questions.json", {"schemaVersion": 1, "questions": [n[0] for n in NEW]})
    write(f"{out}/proposed-links.json", {"schemaVersion": 1, "batchId": BATCH_ID, "existingQuestionLinks": link_records})
    write(f"{out}/distribution-audit.json", audit(bank))


def audit(bank):
    qs = [n[0] for n in NEW]
    hooks = qs + [bank[l[0]][1] for l in LINKS]
    tags = [(n[1], n[3], n[4]) for n in NEW] + [(l[2], l[4], l[5]) for l in LINKS]
    return {
        "schemaVersion": 1, "batchId": BATCH_ID, "auditedOn": CHECKED,
        "state": "editorial_only_awaiting_owner_content_approval",
        "newQuestionCount": len(qs), "reusedQuestionCount": len(LINKS),
        "proposedNewRelationCount": sum(len(q["relatedEventIds"]) for q in qs) + len(LINKS),
        "newQuestionTypes": dict(collections.Counter(q["type"] for q in qs)),
        "newQuestionDifficulties": dict(collections.Counter(q["difficulty"] for q in qs)),
        "hookTypes": dict(collections.Counter(q["type"] for q in hooks)),
        "hookDifficulties": dict(collections.Counter(q["difficulty"] for q in hooks)),
        "newMultipleChoiceCorrectPositions": dict(sorted(collections.Counter(
            str([o["id"] for o in q["options"]].index(q["correctOptionId"]) + 1)
            for q in qs if q["type"] == "multiple_choice").items())),
        "newTrueFalseAnswers": dict(collections.Counter(q["correctOptionId"] for q in qs if q["type"] == "true_false")),
        "hookCollectionMemberships": dict(collections.Counter(c for q in hooks for c in q["collectionIds"])),
        "regionTagMemberships": dict(collections.Counter(r for t in tags for r in t[1])),
        "eraTagMemberships": dict(collections.Counter(e for t in tags for e in t[2])),
        "calendarDayHookCounts": dict(sorted(collections.Counter(t[0] for t in tags).items())),
    }


def main():
    bank = canonical_questions()
    events = set()
    for b in EVENT_BATCHES:
        events |= {e["id"] for e in json.load(open(f"editorial/batches/{b}/draft-events.json"))["events"]}
    build(bank, events)
    ids = [n[0]["id"] for n in NEW]
    assert len(ids) == len(set(ids))
    print(f"{len(NEW)} new drafts, {len(LINKS)} links")


if __name__ == "__main__":
    main()
